apiVersion: v1
kind: Service
metadata:
  name: calculator-gateway-service
spec:
  type: NodePort
  selector:
    app: calculator-gateway
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-add-service
spec:
  type: ClusterIP
  selector:
    app: calculator-add
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-subtract-service
spec:
  type: ClusterIP
  selector:
    app: calculator-subtract
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-multiply-service
spec:
  type: ClusterIP
  selector:
    app: calculator-multiply
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-divide-service
spec:
  type: ClusterIP
  selector:
    app: calculator-divide
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004